# Form implementation generated from reading ui file '/Users/fragalop/Desktop/code/QGISFMV/code/ui/ui_FmvOpenStream.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from qgis.PyQt import QtCore, QtGui, QtWidgets


class Ui_FmvOpenStream(object):
    def setupUi(self, FmvOpenStream):
        FmvOpenStream.setObjectName("FmvOpenStream")
        FmvOpenStream.resize(560, 340)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/imgFMV/images/misc/stream.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        FmvOpenStream.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(FmvOpenStream)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lbl_protocol = QtWidgets.QLabel(parent=FmvOpenStream)
        self.lbl_protocol.setObjectName("lbl_protocol")
        self.horizontalLayout_2.addWidget(self.lbl_protocol)
        self.cmb_protocol = QtWidgets.QComboBox(parent=FmvOpenStream)
        self.cmb_protocol.setObjectName("cmb_protocol")
        self.cmb_protocol.addItem("")
        self.cmb_protocol.addItem("")
        self.cmb_protocol.addItem("")
        self.cmb_protocol.addItem("")
        self.horizontalLayout_2.addWidget(self.cmb_protocol)
        self.lbl_host = QtWidgets.QLabel(parent=FmvOpenStream)
        self.lbl_host.setObjectName("lbl_host")
        self.horizontalLayout_2.addWidget(self.lbl_host)
        self.ln_host = QtWidgets.QLineEdit(parent=FmvOpenStream)
        self.ln_host.setObjectName("ln_host")
        self.horizontalLayout_2.addWidget(self.ln_host)
        self.lbl_port = QtWidgets.QLabel(parent=FmvOpenStream)
        self.lbl_port.setObjectName("lbl_port")
        self.horizontalLayout_2.addWidget(self.lbl_port)
        self.ln_port = QtWidgets.QLineEdit(parent=FmvOpenStream)
        self.ln_port.setObjectName("ln_port")
        self.horizontalLayout_2.addWidget(self.ln_port)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_path = QtWidgets.QHBoxLayout()
        self.horizontalLayout_path.setObjectName("horizontalLayout_path")
        self.lbl_path = QtWidgets.QLabel(parent=FmvOpenStream)
        self.lbl_path.setObjectName("lbl_path")
        self.horizontalLayout_path.addWidget(self.lbl_path)
        self.ln_path = QtWidgets.QLineEdit(parent=FmvOpenStream)
        self.ln_path.setObjectName("ln_path")
        self.horizontalLayout_path.addWidget(self.ln_path)
        self.verticalLayout.addLayout(self.horizontalLayout_path)
        self.lbl_hint = QtWidgets.QTextEdit(parent=FmvOpenStream)
        self.lbl_hint.setReadOnly(True)
        self.lbl_hint.setLineWrapMode(QtWidgets.QTextEdit.LineWrapMode.WidgetWidth)
        self.lbl_hint.setObjectName("lbl_hint")
        self.verticalLayout.addWidget(self.lbl_hint)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_Open = QtWidgets.QPushButton(parent=FmvOpenStream)
        self.btn_Open.setObjectName("btn_Open")
        self.horizontalLayout_3.addWidget(self.btn_Open)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(FmvOpenStream)
        self.cmb_protocol.currentTextChanged['QString'].connect(FmvOpenStream.updateStreamHint) # type: ignore
        self.btn_Open.clicked['bool'].connect(FmvOpenStream.OpenStream) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(FmvOpenStream)

    def retranslateUi(self, FmvOpenStream):
        _translate = QtCore.QCoreApplication.translate
        FmvOpenStream.setWindowTitle(_translate("FmvOpenStream", "Open Stream"))
        self.lbl_protocol.setText(_translate("FmvOpenStream", "Protocol"))
        self.cmb_protocol.setItemText(0, _translate("FmvOpenStream", "UDP"))
        self.cmb_protocol.setItemText(1, _translate("FmvOpenStream", "TCP"))
        self.cmb_protocol.setItemText(2, _translate("FmvOpenStream", "RTP"))
        self.cmb_protocol.setItemText(3, _translate("FmvOpenStream", "RTSP"))
        self.lbl_host.setText(_translate("FmvOpenStream", "Host"))
        self.ln_host.setPlaceholderText(_translate("FmvOpenStream", "127.0.0.1"))
        self.lbl_port.setText(_translate("FmvOpenStream", "Port"))
        self.ln_port.setPlaceholderText(_translate("FmvOpenStream", "5005"))
        self.lbl_path.setText(_translate("FmvOpenStream", "Path"))
        self.ln_path.setPlaceholderText(_translate("FmvOpenStream", "/stream (RTSP only)"))
        self.btn_Open.setText(_translate("FmvOpenStream", "Connect"))
