# Form implementation generated from reading ui file '/Users/fragalop/Desktop/code/QGISFMV/code/ui/ui_FmvBrightnessContrast.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from qgis.PyQt import QtCore, QtGui, QtWidgets


class Ui_FmvBrightnessContrast(object):
    def setupUi(self, FmvBrightnessContrast):
        FmvBrightnessContrast.setObjectName("FmvBrightnessContrast")
        FmvBrightnessContrast.resize(360, 180)
        FmvBrightnessContrast.setMinimumSize(QtCore.QSize(320, 160))
        FmvBrightnessContrast.setMaximumSize(QtCore.QSize(16777215, 200))
        self.verticalLayout = QtWidgets.QVBoxLayout(FmvBrightnessContrast)
        self.verticalLayout.setContentsMargins(12, 12, 12, 12)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.FieldGrowthPolicy.ExpandingFieldsGrow)
        self.formLayout.setHorizontalSpacing(12)
        self.formLayout.setVerticalSpacing(10)
        self.formLayout.setObjectName("formLayout")
        self.lblBrightness = QtWidgets.QLabel(parent=FmvBrightnessContrast)
        self.lblBrightness.setObjectName("lblBrightness")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblBrightness)
        self.brightnessSlider = QtWidgets.QSlider(parent=FmvBrightnessContrast)
        self.brightnessSlider.setMinimumSize(QtCore.QSize(0, 28))
        self.brightnessSlider.setMinimum(-100)
        self.brightnessSlider.setMaximum(100)
        self.brightnessSlider.setTickPosition(QtWidgets.QSlider.TickPosition.TicksBelow)
        self.brightnessSlider.setTickInterval(10)
        self.brightnessSlider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.brightnessSlider.setObjectName("brightnessSlider")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.brightnessSlider)
        self.lblContrast = QtWidgets.QLabel(parent=FmvBrightnessContrast)
        self.lblContrast.setObjectName("lblContrast")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblContrast)
        self.contrastSlider = QtWidgets.QSlider(parent=FmvBrightnessContrast)
        self.contrastSlider.setMinimumSize(QtCore.QSize(0, 28))
        self.contrastSlider.setMinimum(-100)
        self.contrastSlider.setMaximum(100)
        self.contrastSlider.setTickPosition(QtWidgets.QSlider.TickPosition.TicksBelow)
        self.contrastSlider.setTickInterval(10)
        self.contrastSlider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.contrastSlider.setObjectName("contrastSlider")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.contrastSlider)
        self.verticalLayout.addLayout(self.formLayout)
        self.horizontalLayoutButtons = QtWidgets.QHBoxLayout()
        self.horizontalLayoutButtons.setObjectName("horizontalLayoutButtons")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayoutButtons.addItem(spacerItem)
        self.btn_reset = QtWidgets.QPushButton(parent=FmvBrightnessContrast)
        self.btn_reset.setMinimumSize(QtCore.QSize(80, 30))
        self.btn_reset.setObjectName("btn_reset")
        self.horizontalLayoutButtons.addWidget(self.btn_reset)
        self.verticalLayout.addLayout(self.horizontalLayoutButtons)

        self.retranslateUi(FmvBrightnessContrast)
        self.brightnessSlider.valueChanged['int'].connect(FmvBrightnessContrast.onBrightnessChanged) # type: ignore
        self.contrastSlider.valueChanged['int'].connect(FmvBrightnessContrast.onContrastChanged) # type: ignore
        self.btn_reset.clicked.connect(FmvBrightnessContrast.resetValues) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(FmvBrightnessContrast)

    def retranslateUi(self, FmvBrightnessContrast):
        _translate = QtCore.QCoreApplication.translate
        FmvBrightnessContrast.setWindowTitle(_translate("FmvBrightnessContrast", "Brightness / Contrast"))
        self.lblBrightness.setText(_translate("FmvBrightnessContrast", "Brightness"))
        self.lblContrast.setText(_translate("FmvBrightnessContrast", "Contrast"))
        self.btn_reset.setText(_translate("FmvBrightnessContrast", "Reset"))
