# Form implementation generated from reading ui file '/Users/fragalop/Desktop/code/QGISFMV/code/ui/ui_FmvMultiplexer.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from qgis.PyQt import QtCore, QtGui, QtWidgets


class Ui_VideoMultiplexer(object):
    def setupUi(self, VideoMultiplexer):
        VideoMultiplexer.setObjectName("VideoMultiplexer")
        VideoMultiplexer.resize(520, 280)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/imgFMV/images/misc/multiplexer.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        VideoMultiplexer.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(VideoMultiplexer)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=VideoMultiplexer)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.ln_inputVideo = QtWidgets.QLineEdit(parent=VideoMultiplexer)
        self.ln_inputVideo.setReadOnly(True)
        self.ln_inputVideo.setObjectName("ln_inputVideo")
        self.horizontalLayout_4.addWidget(self.ln_inputVideo)
        self.btn_openVideo = QtWidgets.QPushButton(parent=VideoMultiplexer)
        self.btn_openVideo.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_openVideo.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/imgFMV/images/misc/opened-folder.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_openVideo.setIcon(icon1)
        self.btn_openVideo.setObjectName("btn_openVideo")
        self.horizontalLayout_4.addWidget(self.btn_openVideo)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.label_2 = QtWidgets.QLabel(parent=VideoMultiplexer)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ln_inputMeta = QtWidgets.QLineEdit(parent=VideoMultiplexer)
        self.ln_inputMeta.setReadOnly(True)
        self.ln_inputMeta.setObjectName("ln_inputMeta")
        self.horizontalLayout.addWidget(self.ln_inputMeta)
        self.btn_openTelemetry = QtWidgets.QPushButton(parent=VideoMultiplexer)
        self.btn_openTelemetry.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_openTelemetry.setText("")
        self.btn_openTelemetry.setIcon(icon1)
        self.btn_openTelemetry.setObjectName("btn_openTelemetry")
        self.horizontalLayout.addWidget(self.btn_openTelemetry)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label_3 = QtWidgets.QLabel(parent=VideoMultiplexer)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ln_outputVideo = QtWidgets.QLineEdit(parent=VideoMultiplexer)
        self.ln_outputVideo.setObjectName("ln_outputVideo")
        self.horizontalLayout_2.addWidget(self.ln_outputVideo)
        self.btn_saveVideo = QtWidgets.QPushButton(parent=VideoMultiplexer)
        self.btn_saveVideo.setText("")
        self.btn_saveVideo.setIcon(icon1)
        self.btn_saveVideo.setObjectName("btn_saveVideo")
        self.horizontalLayout_2.addWidget(self.btn_saveVideo)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.chk_addManager = QtWidgets.QCheckBox(parent=VideoMultiplexer)
        self.chk_addManager.setChecked(True)
        self.chk_addManager.setObjectName("chk_addManager")
        self.verticalLayout.addWidget(self.chk_addManager)
        self.bt_createMISB = QtWidgets.QPushButton(parent=VideoMultiplexer)
        self.bt_createMISB.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.bt_createMISB.setObjectName("bt_createMISB")
        self.verticalLayout.addWidget(self.bt_createMISB)

        self.retranslateUi(VideoMultiplexer)
        self.bt_createMISB.clicked.connect(VideoMultiplexer.CreateMISB) # type: ignore
        self.btn_openVideo.clicked.connect(VideoMultiplexer.OpenVideoFile) # type: ignore
        self.btn_openTelemetry.clicked.connect(VideoMultiplexer.OpenTelemetryFile) # type: ignore
        self.btn_saveVideo.clicked.connect(VideoMultiplexer.OpenOutputFile) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(VideoMultiplexer)

    def retranslateUi(self, VideoMultiplexer):
        _translate = QtCore.QCoreApplication.translate
        VideoMultiplexer.setWindowTitle(_translate("VideoMultiplexer", "Video Multiplexer"))
        self.label.setText(_translate("VideoMultiplexer", "Source video"))
        self.label_2.setText(_translate("VideoMultiplexer", "Telemetry file (.csv, .txt, .log)"))
        self.label_3.setText(_translate("VideoMultiplexer", "Output video (.ts)"))
        self.chk_addManager.setText(_translate("VideoMultiplexer", "Add to the manager"))
        self.bt_createMISB.setText(_translate("VideoMultiplexer", "Accept"))
