# Form implementation generated from reading ui file '/Users/fragalop/Desktop/code/QGISFMV/code/ui/ui_FmvAlertRule.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from qgis.PyQt import QtCore, QtGui, QtWidgets


class Ui_FmvAlertRule(object):
    def setupUi(self, FmvAlertRule):
        FmvAlertRule.setObjectName("FmvAlertRule")
        FmvAlertRule.resize(420, 200)
        FmvAlertRule.setMinimumSize(QtCore.QSize(360, 180))
        FmvAlertRule.setLocale(QtCore.QLocale(QtCore.QLocale.Language.English, QtCore.QLocale.Country.UnitedStates))
        self.verticalLayout = QtWidgets.QVBoxLayout(FmvAlertRule)
        self.verticalLayout.setContentsMargins(12, 12, 12, 12)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setHorizontalSpacing(12)
        self.formLayout.setVerticalSpacing(8)
        self.formLayout.setObjectName("formLayout")
        self.lblField = QtWidgets.QLabel(parent=FmvAlertRule)
        self.lblField.setObjectName("lblField")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblField)
        self.cmbField = QtWidgets.QComboBox(parent=FmvAlertRule)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbField.sizePolicy().hasHeightForWidth())
        self.cmbField.setSizePolicy(sizePolicy)
        self.cmbField.setObjectName("cmbField")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.cmbField)
        self.lblOperator = QtWidgets.QLabel(parent=FmvAlertRule)
        self.lblOperator.setObjectName("lblOperator")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblOperator)
        self.cmbOperator = QtWidgets.QComboBox(parent=FmvAlertRule)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbOperator.sizePolicy().hasHeightForWidth())
        self.cmbOperator.setSizePolicy(sizePolicy)
        self.cmbOperator.setObjectName("cmbOperator")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.cmbOperator)
        self.lblThreshold = QtWidgets.QLabel(parent=FmvAlertRule)
        self.lblThreshold.setObjectName("lblThreshold")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblThreshold)
        self.lnThreshold = QtWidgets.QLineEdit(parent=FmvAlertRule)
        self.lnThreshold.setClearButtonEnabled(True)
        self.lnThreshold.setObjectName("lnThreshold")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lnThreshold)
        self.verticalLayout.addLayout(self.formLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 8, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=FmvAlertRule)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(FmvAlertRule)
        self.buttonBox.accepted.connect(FmvAlertRule.accept) # type: ignore
        self.buttonBox.rejected.connect(FmvAlertRule.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(FmvAlertRule)

    def retranslateUi(self, FmvAlertRule):
        _translate = QtCore.QCoreApplication.translate
        FmvAlertRule.setWindowTitle(_translate("FmvAlertRule", "Alert Rule"))
        self.lblField.setText(_translate("FmvAlertRule", "Field to monitor"))
        self.lblOperator.setText(_translate("FmvAlertRule", "Condition"))
        self.lblThreshold.setText(_translate("FmvAlertRule", "Threshold"))
        self.lnThreshold.setPlaceholderText(_translate("FmvAlertRule", "Numeric value"))
