# Form implementation generated from reading ui file '/Users/fragalop/Desktop/code/QGISFMV/code/ui/ui_FmvAbout.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from qgis.PyQt import QtCore, QtGui, QtWidgets


class Ui_FmvAbout(object):
    def setupUi(self, FmvAbout):
        FmvAbout.setObjectName("FmvAbout")
        FmvAbout.resize(643, 559)
        FmvAbout.setMinimumSize(QtCore.QSize(200, 250))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/imgFMV/images/status/Information.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        FmvAbout.setWindowIcon(icon)
        FmvAbout.setLocale(QtCore.QLocale(QtCore.QLocale.Language.English, QtCore.QLocale.Country.UnitedStates))
        self.verticalLayout = QtWidgets.QVBoxLayout(FmvAbout)
        self.verticalLayout.setObjectName("verticalLayout")
        self.webView = QtWidgets.QTextBrowser(parent=FmvAbout)
        self.webView.setOpenExternalLinks(True)
        self.webView.setObjectName("webView")
        self.verticalLayout.addWidget(self.webView)

        self.retranslateUi(FmvAbout)
        QtCore.QMetaObject.connectSlotsByName(FmvAbout)

    def retranslateUi(self, FmvAbout):
        _translate = QtCore.QCoreApplication.translate
        FmvAbout.setWindowTitle(_translate("FmvAbout", "About"))
