# Form implementation generated from reading ui file '/Users/fragalop/Desktop/code/QGISFMV/code/ui/ui_FmvTableProgress.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from qgis.PyQt import QtCore, QtGui, QtWidgets


class Ui_FmvTableProgress(object):
    def setupUi(self, FmvTableProgress):
        FmvTableProgress.setObjectName("FmvTableProgress")
        self.verticalLayout = QtWidgets.QVBoxLayout(FmvTableProgress)
        self.verticalLayout.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pbar = QtWidgets.QProgressBar(parent=FmvTableProgress)
        self.pbar.setMinimumSize(QtCore.QSize(0, 24))
        self.pbar.setMaximumSize(QtCore.QSize(16777215, 30))
        self.pbar.setProperty("value", 0)
        self.pbar.setObjectName("pbar")
        self.verticalLayout.addWidget(self.pbar)

        self.retranslateUi(FmvTableProgress)
        QtCore.QMetaObject.connectSlotsByName(FmvTableProgress)

    def retranslateUi(self, FmvTableProgress):
        pass
