# Form implementation generated from reading ui file '/Users/fragalop/Desktop/code/QGISFMV/code/ui/ui_FmvVideoInfo.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from qgis.PyQt import QtCore, QtGui, QtWidgets


class Ui_FmvVideoInfo(object):
    def setupUi(self, FmvVideoInfo):
        FmvVideoInfo.setObjectName("FmvVideoInfo")
        FmvVideoInfo.resize(900, 800)
        FmvVideoInfo.setMinimumSize(QtCore.QSize(640, 480))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/imgFMV/images/export/video-info.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        FmvVideoInfo.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(FmvVideoInfo)
        self.verticalLayout.setContentsMargins(8, 8, 8, 8)
        self.verticalLayout.setObjectName("verticalLayout")
        self.treeView = QtWidgets.QTreeView(parent=FmvVideoInfo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.treeView.sizePolicy().hasHeightForWidth())
        self.treeView.setSizePolicy(sizePolicy)
        self.treeView.setAlternatingRowColors(True)
        self.treeView.setRootIsDecorated(True)
        self.treeView.setUniformRowHeights(True)
        self.treeView.setObjectName("treeView")
        self.treeView.header().setStretchLastSection(True)
        self.verticalLayout.addWidget(self.treeView)

        self.retranslateUi(FmvVideoInfo)
        QtCore.QMetaObject.connectSlotsByName(FmvVideoInfo)

    def retranslateUi(self, FmvVideoInfo):
        _translate = QtCore.QCoreApplication.translate
        FmvVideoInfo.setWindowTitle(_translate("FmvVideoInfo", "Video Information"))
