
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys


version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "be7e4e46dc010bc237485081b42e541190754285",
 "version": "2.1.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
